Домашнее задание hw3 по Базе данных.
SergeFox02/HWSchoolHogwards pull request #2
Opened 2022-04-06 18:14 UTC by SergeFox02

2022-04-06 21:53 UTC, rmuhamedgaliev requested changes
Требуются правки

2022-04-06 21:53 UTC, rmuhamedgaliev commented on src/main/java/ru/hogwarts/school/service/impl/FacultyServiceImpl.java
@Autowire забыл, в ответ напиши для чего он нужен

2022-04-06 21:53 UTC, rmuhamedgaliev commented on src/main/java/ru/hogwarts/school/service/impl/FacultyServiceImpl.java
Другой сейрвис так же проверь

2022-04-07 17:57 UTC, SergeFox02 commented on src/main/java/ru/hogwarts/school/service/impl/FacultyServiceImpl.java
@Autowire нужен для того чтобы Spring автоматически определял, что для создания нашего сервиса требуется bean того типа который мы определяем (или наследник). Spring найдёт его у себя. В нашем случае  подставит зависимость FacultyRepository в bean FacultyServuceImpl/.

2022-04-07 19:54 UTC, rmuhamedgaliev approved these changes
Принято

2022-04-13 06:17 UTC, merged